### ISSUE TITLE
Windows compile error

### ISSUE THREAD

**Issue by duzenko** [neslib/DelphiLearnOpenGL#3]
1. Go to `DelphiLearnOpenGL-master\Tutorials\1.GettingStarted\1.HelloWindow`
2. Open `T101HelloWindow.dpr`
3. Try compiling 
`[dcc32 Fatal Error] Sample.Androidapi.AppGlue.pas(15): F2613 Unit 'Posix.SysTypes' not found.`

Please advise

![image](https://user-images.githubusercontent.com/1481807/67423009-28f0f100-f5dc-11e9-8da5-864569734056.png)

**Comment by neslib** [comment]
Oops. The Sample.Androidapi.AppGlue unit should not be included in the project for Windows builds. You can remove it from the project manager.

**Comment by duzenko** [comment]
I can surely fix this on my side. Reporting here so that it can also be fixed on yours.

**Comment by neslib** [comment]
OK. Thanks. Should be fixed now
